### ISSUE TITLE
[Tracking] Refactor TODOs

### ISSUE THREAD

**Issue by yyx990803** [vuejs/vue-vapor#293]
- [ ] further set props optimizations on static keys
- [ ] props setting metadata optimization
- [ ] reuse htmlNesting
- [ ] vFor reuse sequence from core
- [ ] createVaporApp should reuse more from createApp
- [ ] setStyle etc. reuse from runtime-dom
  - check how svelte / solid handle style
- [ ] `on` is pulling in all the modifier code
- [ ] `setDynamicProps` is pulling all the props code <- `fallthroughAttrs` <- `setupComponent`
- [ ] `setup()` returning object is only needed in `__DEV__` (hmr)
- [ ] simple component
- [ ] dynamic binding constant detection
- [ ] simplify `renderEffect`
  - [ ] only 1 effect per scope? (need bench)
  - [ ] binding inline caching
  - [ ] error if no instance
  - [ ] remove memo
